# Generated by Django 5.2.4 on 2026-02-18 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#000000', help_text='Color en formato hexadecimal', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Noticia',
                'verbose_name_plural': 'Categorías de Noticias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, unique=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Establecimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Establecimiento',
                'verbose_name_plural': 'Tipos de Establecimiento',
                'db_table': 'tipo_establecimiento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('profesion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesión')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Identificación')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/', verbose_name='Imagen de perfil')),
                ('avatar_url', models.URLField(blank=True, help_text='URL de Cloudinary para avatar predeterminado', null=True, verbose_name='Avatar predeterminado')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popayan_all_tour1.roles', verbose_name='Rol')),
                ('tipo_establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popayan_all_tour1.tipoestablecimiento', verbose_name='Tipo de Establecimiento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('contenido', models.TextField(help_text='Contenido completo de la noticia')),
                ('resumen', models.TextField(blank=True, help_text='Resumen breve para vista previa', max_length=500, null=True)),
                ('imagen_principal', models.ImageField(help_text='Imagen principal de la noticia', upload_to='noticias/')),
                ('pie_imagen', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('publicada', models.BooleanField(default=False)),
                ('destacada', models.BooleanField(default=False, help_text='Marcar como noticia destacada')),
                ('visitas_totales', models.PositiveIntegerField(default=0, editable=False)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_creadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='popayan_all_tour1.categorianoticia')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/adicionales/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='popayan_all_tour1.noticia')),
            ],
            options={
                'verbose_name': 'Imagen Adicional',
                'verbose_name_plural': 'Imágenes Adicionales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('horario_aten', models.TextField(max_length=200, verbose_name='Horario de Atención')),
                ('direccion', models.TextField(max_length=200, verbose_name='Dirección')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='establecimientos/', verbose_name='Imagen')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen (Cloudinary)')),
                ('url_mas_info', models.URLField(verbose_name='URL para más información')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresario', models.ForeignKey(blank=True, limit_choices_to={'rol__rol': 'empresario'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to=settings.AUTH_USER_MODEL, verbose_name='Empresario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to='popayan_all_tour1.tipoestablecimiento', verbose_name='Tipo de Establecimiento')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VisitaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='popayan_all_tour1.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_visitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita a Noticia',
                'verbose_name_plural': 'Visitas a Noticias',
                'ordering': ['-fecha_visita'],
            },
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['-fecha_publicacion'], name='popayan_all_fecha_p_c1b533_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['-visitas_totales'], name='popayan_all_visitas_0f8251_idx'),
        ),
        migrations.AddIndex(
            model_name='visitanoticia',
            index=models.Index(fields=['noticia', 'usuario'], name='popayan_all_noticia_86fdaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitanoticia',
            unique_together={('noticia', 'usuario')},
        ),
    ]
